/**
 * JWX Delivery Timeline — end-to-end test suite (Playwright / Chromium).
 *
 * Two pages are used:
 *   /             – index.html with placeholder credentials → cloudEnabled() false
 *   /test-index.html – generated by global-setup.js with fake creds → cloudEnabled() true
 *
 * All JSONBin API calls are intercepted with page.route() so no real network
 * traffic occurs during the cloud-sync tests.
 */

const { test, expect } = require('@playwright/test');
const path = require('path');
const fs = require('fs');
const os = require('os');

// ─── shared helpers ──────────────────────────────────────────────────────────

/** Wait for init() to finish setting the status (not '—' and not 'Syncing…'). */
async function waitForInit(page) {
  await page.waitForFunction(
    () => {
      const el = document.getElementById('status');
      const t = el ? el.textContent : '';
      return t !== '—' && t !== 'Syncing…'; // '—' U+2014, '…' U+2026
    },
    { timeout: 15_000 }
  );
}

/** Wait for at least one .bar to appear in the DOM. */
async function waitForBars(page) {
  await page.waitForSelector('.bar', { timeout: 15_000 });
}

/**
 * Route all api.jsonbin.io calls:
 *   GET  /v3/b/:id/latest → { record: data || {} }
 *   PUT  /v3/b/:id        → { record: <request body>, metadata: { id: 'test' } }
 *   fail = true           → abort the connection
 */
async function mockCloud(page, { data = null, fail = false, version = 1 } = {}) {
  await page.route('**/api.jsonbin.io/**', async route => {
    if (fail) { await route.abort('failed'); return; }

    if (route.request().method() === 'GET') {
      const record = data
        ? { app: 'jwx-timeline', version, exportedAt: new Date().toISOString(), teams: [], tasks: data }
        : {};
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ record }),
      });
    } else {
      // PUT — echo back the body so saveToCloud can confirm success
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ record: {}, metadata: { id: 'test' } }),
      });
    }
  });
}

// ─── Page Health ─────────────────────────────────────────────────────────────

test.describe('Page Health', () => {
  test('loads without JavaScript errors', async ({ page }) => {
    const errors = [];
    page.on('pageerror', err => errors.push(err.message));
    await page.goto('/');
    await waitForInit(page);
    expect(errors, `unexpected JS errors: ${errors.join('; ')}`).toHaveLength(0);
  });

  test('renders all 14 baseline bars', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await expect(page.locator('.bar')).toHaveCount(14);
  });

  test('MVP date chip is populated', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const text = await page.locator('#m-mvp').textContent();
    expect(text).not.toBe('—');
    expect(text.trim().length).toBeGreaterThan(2);
  });

  test('GA date chip is populated', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const text = await page.locator('#m-ga').textContent();
    expect(text).not.toBe('—');
  });

  test('Total Span chip is populated', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await expect(page.locator('#m-span')).toContainText('weeks');
  });

  test('all toolbar buttons are present and enabled', async ({ page }) => {
    await page.goto('/');
    for (const id of ['save', 'export', 'import', 'addteam', 'reset']) {
      const btn = page.locator(`#${id}`);
      await expect(btn).toBeVisible();
      await expect(btn).not.toBeDisabled();
    }
  });

  test('four default lane headers are rendered', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await expect(page.locator('.lhead')).toHaveCount(4);
  });
});

// ─── Export ──────────────────────────────────────────────────────────────────

test.describe('Export', () => {
  test('export button triggers a file download', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const dlPromise = page.waitForEvent('download');
    await page.click('#export');
    const dl = await dlPromise;
    expect(dl.suggestedFilename()).toMatch(/^jwx-timeline-\d{4}-\d{2}-\d{2}\.json$/);
  });

  test('exported JSON has correct envelope fields', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const dlPromise = page.waitForEvent('download');
    await page.click('#export');
    const dl = await dlPromise;
    const tmp = path.join(os.tmpdir(), `export-${Date.now()}.json`);
    await dl.saveAs(tmp);
    const data = JSON.parse(fs.readFileSync(tmp, 'utf8'));
    expect(data.app).toBe('jwx-timeline');
    expect(data.version).toBe(2);
    expect(data.exportedAt).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(Array.isArray(data.tasks)).toBe(true);
    expect(data.tasks).toHaveLength(14);
  });

  test('each exported task has required fields', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const dlPromise = page.waitForEvent('download');
    await page.click('#export');
    const dl = await dlPromise;
    const tmp = path.join(os.tmpdir(), `export-fields-${Date.now()}.json`);
    await dl.saveAs(tmp);
    const { tasks } = JSON.parse(fs.readFileSync(tmp, 'utf8'));
    for (const t of tasks) {
      expect(t).toHaveProperty('id');
      expect(t).toHaveProperty('s');
      expect(t).toHaveProperty('dur');
      expect(t).toHaveProperty('team');
    }
  });

  test('export shows success status', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await page.click('#export');
    await expect(page.locator('#status')).toContainText('Exported');
  });
});

// ─── Import ──────────────────────────────────────────────────────────────────

test.describe('Import', () => {
  test('importing a valid exported file shows success status', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);

    // round-trip: export first, then import back
    const dlPromise = page.waitForEvent('download');
    await page.click('#export');
    const dl = await dlPromise;
    const tmp = path.join(os.tmpdir(), `roundtrip-${Date.now()}.json`);
    await dl.saveAs(tmp);

    await page.locator('#importFile').setInputFiles(tmp);
    await expect(page.locator('#status')).toContainText('Imported', { timeout: 5_000 });
  });

  test('import preserves task positions from the file', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);

    // Build a payload where viewability starts at week 7 (non-default is week 3)
    const modified = [{ id: 'viewability', s: 7, dur: 6, team: 'pubmon' }];
    const tmp = path.join(os.tmpdir(), `overlay-${Date.now()}.json`);
    fs.writeFileSync(tmp, JSON.stringify({ app: 'jwx-timeline', version: 1, tasks: modified }));
    await page.locator('#importFile').setInputFiles(tmp);
    await expect(page.locator('#status')).toContainText('Imported', { timeout: 5_000 });

    // Bar left = s * WEEKW px.  WEEKW defaults to 88, so week 7 → 616 px.
    const left = await page.locator('.bar[data-id="viewability"]').evaluate(el => el.style.left);
    expect(parseFloat(left)).toBeCloseTo(7 * 88, 0);
  });

  test('importing invalid JSON shows error status', async ({ page }) => {
    await page.goto('/');
    const tmp = path.join(os.tmpdir(), `bad-${Date.now()}.json`);
    fs.writeFileSync(tmp, 'this is not json');
    await page.locator('#importFile').setInputFiles(tmp);
    await expect(page.locator('#status')).toContainText('failed', { timeout: 5_000 });
  });

  test('importing JSON with empty tasks array shows error status', async ({ page }) => {
    await page.goto('/');
    const tmp = path.join(os.tmpdir(), `empty-${Date.now()}.json`);
    fs.writeFileSync(tmp, JSON.stringify({ app: 'jwx-timeline', tasks: [] }));
    await page.locator('#importFile').setInputFiles(tmp);
    await expect(page.locator('#status')).toContainText('failed', { timeout: 5_000 });
  });

  test('timeline still shows 14 bars after a failed import', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const tmp = path.join(os.tmpdir(), `bad2-${Date.now()}.json`);
    fs.writeFileSync(tmp, '{}');
    await page.locator('#importFile').setInputFiles(tmp);
    await expect(page.locator('#status')).toContainText('failed', { timeout: 5_000 });
    // original bars should still be there
    await expect(page.locator('.bar')).toHaveCount(14);
  });
});

// ─── Save & Persistence ──────────────────────────────────────────────────────

test.describe('Save & Persistence', () => {
  test('save now updates the status bar', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await page.click('#save');
    await expect(page.locator('#status')).toContainText('Saved', { timeout: 5_000 });
  });

  test('saved data survives a page reload', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await page.click('#save');
    await page.reload();
    await waitForBars(page);
    await expect(page.locator('.bar')).toHaveCount(14);
    await expect(page.locator('#status')).toContainText('Restored');
  });

  test('save writes a v2 envelope to localStorage', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await page.click('#save');
    const stored = await page.evaluate(() => localStorage.getItem('jwx_timeline_state_final'));
    expect(stored).not.toBeNull();
    const parsed = JSON.parse(stored);
    expect(parsed.version).toBe(2);
    expect(Array.isArray(parsed.tasks)).toBe(true);
    expect(parsed.tasks).toHaveLength(14);
  });
});

// ─── Persistence v2 ──────────────────────────────────────────────────────────

const V2 = (tasks) => JSON.stringify({
  app: 'jwx-timeline', version: 2, exportedAt: '2026-08-03T00:00:00.000Z', teams: [], tasks,
});

test.describe('Persistence v2', () => {
  test('a v1 bare array migrates with positions preserved', async ({ page }) => {
    await page.goto('/');
    await page.evaluate(() => localStorage.setItem('jwx_timeline_state_final',
      JSON.stringify([{ id: 'viewability', s: 7, dur: 6.5, team: 'auction' }])));
    await page.reload();
    await waitForBars(page);
    await expect(page.locator('.bar')).toHaveCount(14);
    const left = await page.locator('.bar[data-id="viewability"]').evaluate(el => el.style.left);
    expect(parseFloat(left)).toBeCloseTo(7 * 88, 0);
    // scope/status come from BASELINE, which v1 never persisted
    await expect(page.locator('.bar[data-id="jwdata"] > .bar-fill.indev')).toHaveCount(1);
  });

  test('a v2 payload is loaded verbatim, including a deleted item', async ({ page }) => {
    await page.goto('/');
    await page.evaluate(v2 => localStorage.setItem('jwx_timeline_state_final', v2), V2([
      { id: 'viewability', name: 'Ad viewability policy setup', team: 'pubmon', s: 3, dur: 6.5, size: 'XL', scope: 'MVP', status: 'done' },
      { id: 'gam', name: 'GAM mediation Spotlight (pre-roll)', team: 'exchange', s: 1, dur: 5.5, size: 'L', scope: 'GA', status: 'planned' },
    ]));
    await page.reload();
    await waitForBars(page);
    await expect(page.locator('.bar')).toHaveCount(2);
    await expect(page.locator('.bar[data-id="playback"]')).toHaveCount(0);
  });

  test('an explicitly empty v2 plan stays empty across reload', async ({ page }) => {
    await page.goto('/');
    await page.evaluate(v2 => localStorage.setItem('jwx_timeline_state_final', v2), V2([]));
    await page.reload();
    await waitForInit(page);
    await expect(page.locator('.bar')).toHaveCount(0);
    await expect(page.locator('#status')).toContainText('No work items');
    await expect(page.locator('#m-mvp')).toHaveText('—');
  });

  test('a corrupt payload falls back to BASELINE', async ({ page }) => {
    await page.goto('/');
    await page.evaluate(() => localStorage.setItem('jwx_timeline_state_final',
      JSON.stringify({ app: 'jwx-timeline', version: 2, tasks: 'not-an-array' })));
    await page.reload();
    await waitForBars(page);
    await expect(page.locator('.bar')).toHaveCount(14);
  });

  test('a v2 payload whose every item is invalid falls back to BASELINE', async ({ page }) => {
    await page.goto('/');
    // items with no usable id sanitize away — that is corruption, not an empty plan
    await page.evaluate(v2 => localStorage.setItem('jwx_timeline_state_final', v2),
      V2([{ name: 'no id' }, { id: '', name: 'blank id' }]));
    await page.reload();
    await waitForBars(page);
    await expect(page.locator('.bar')).toHaveCount(14);
  });

  test('sanitizeTasks coerces out-of-range and unknown values', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const out = await page.evaluate(() => window.sanitizeTasks([
      { id: 'a', scope: 'nonsense', status: 'wat', dur: -5, s: -3, size: 'XXL' },
      { id: 'b', name: 'ok', team: 'exchange', s: 2, dur: 1.5, size: 'M', scope: 'MVP', status: 'done' },
      { id: 'a', name: 'duplicate id' },
      { name: 'no id at all' },
    ]));
    expect(out).toHaveLength(2);
    expect(out[0]).toMatchObject({ id: 'a', name: 'Untitled item', team: 'pubmon', s: 0, dur: 1, size: '—', scope: 'GA', status: 'planned' });
    expect(out[1]).toMatchObject({ id: 'b', scope: 'MVP', status: 'done', dur: 1.5 });
  });

  test('a v2 cloud payload is loaded verbatim', async ({ page }) => {
    await mockCloud(page, {
      version: 2,
      data: [{ id: 'solo', name: 'Only item', team: 'auction', s: 4, dur: 2, size: 'M', scope: 'MVP', status: 'done' }],
    });
    await page.goto('/test-index.html');
    await expect(page.locator('#status')).toContainText('Synced from cloud', { timeout: 10_000 });
    await expect(page.locator('.bar')).toHaveCount(1);
    await expect(page.locator('.bar[data-id="solo"] > .bar-fill.done')).toHaveCount(1);
  });
});

// ─── Reset ───────────────────────────────────────────────────────────────────

test.describe('Reset to Baseline', () => {
  test('reset button shows baseline status', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await page.click('#reset');
    await expect(page.locator('#status')).toContainText('baseline', { timeout: 5_000 });
  });

  test('all 14 bars are still visible after reset', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await page.click('#reset');
    await waitForBars(page);
    await expect(page.locator('.bar')).toHaveCount(14);
  });

  test('reset clears localStorage', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    // save first so there is something to clear
    await page.click('#save');
    await page.click('#reset');
    const stored = await page.evaluate(() => localStorage.getItem('jwx_timeline_state_final'));
    expect(stored).toBeNull();
  });

  test('viewability bar returns to BASELINE position (week 3) after reset', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);

    // Import a modified position first
    const tmp = path.join(os.tmpdir(), `pre-reset-${Date.now()}.json`);
    fs.writeFileSync(tmp, JSON.stringify({ app: 'jwx-timeline', tasks: [{ id: 'viewability', s: 10, dur: 6, team: 'pubmon' }] }));
    await page.locator('#importFile').setInputFiles(tmp);
    await expect(page.locator('#status')).toContainText('Imported', { timeout: 5_000 });

    // Reset
    await page.click('#reset');
    await waitForBars(page);

    // BASELINE has viewability at s=3 → left = 3 * 88 = 264 px
    const left = await page.locator('.bar[data-id="viewability"]').evaluate(el => el.style.left);
    expect(parseFloat(left)).toBeCloseTo(3 * 88, 0);
  });
});

// ─── Team Management ─────────────────────────────────────────────────────────

test.describe('Team Management', () => {
  test('add team creates a new lane', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const before = await page.locator('.lhead').count();
    page.once('dialog', d => d.accept('QA Team'));
    await page.click('#addteam');
    await page.waitForFunction(n => document.querySelectorAll('.lhead').length > n, before, { timeout: 5_000 });
    await expect(page.locator('.lhead')).toHaveCount(before + 1);
  });

  test('new lane header contains the team name', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    page.once('dialog', d => d.accept('Analytics Squad'));
    await page.click('#addteam');
    await page.waitForFunction(() =>
      Array.from(document.querySelectorAll('.lhead')).some(el => el.textContent.includes('Analytics Squad')),
      { timeout: 5_000 }
    );
    await expect(page.locator('.lhead').last()).toContainText('Analytics Squad');
  });

  test('dismissing add-team dialog adds no lane', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const before = await page.locator('.lhead').count();
    page.once('dialog', d => d.dismiss());
    await page.click('#addteam');
    await page.waitForTimeout(300);
    await expect(page.locator('.lhead')).toHaveCount(before);
  });

  test('empty custom lane can be removed', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    page.once('dialog', d => d.accept('Temp Team ZZZ'));
    await page.click('#addteam');
    await page.waitForFunction(() =>
      Array.from(document.querySelectorAll('.lhead')).some(el => el.textContent.includes('Temp Team ZZZ')),
      { timeout: 5_000 }
    );
    const before = await page.locator('.lhead').count();

    const lheads = page.locator('.lhead');
    const n = await lheads.count();
    for (let i = 0; i < n; i++) {
      if ((await lheads.nth(i).textContent()).includes('Temp Team ZZZ')) {
        await lheads.nth(i).locator('.lrm').click();
        break;
      }
    }
    await page.waitForFunction(c => document.querySelectorAll('.lhead').length < c, before, { timeout: 5_000 });
    await expect(page.locator('.lhead')).toHaveCount(before - 1);
  });

  test('removing a team that has tasks shows a warning', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    // removeTeam('pubmon') is a global function; pubmon always has BASELINE tasks
    await page.evaluate(() => window.removeTeam('pubmon'));
    await expect(page.locator('#status')).toContainText("team's items");
    // lane must still be there
    await expect(page.locator('.lhead')).toHaveCount(4);
  });
});

// ─── cloudEnabled() guard ────────────────────────────────────────────────────

test.describe('cloudEnabled() guard', () => {
  test('returns false on index.html (placeholder credentials)', async ({ page }) => {
    await page.goto('/');
    await waitForInit(page);
    const enabled = await page.evaluate(() => window.cloudEnabled());
    expect(enabled).toBe(false);
  });

  test('returns true on test-index.html (non-placeholder credentials)', async ({ page }) => {
    await mockCloud(page);
    await page.goto('/test-index.html');
    await waitForInit(page);
    const enabled = await page.evaluate(() => window.cloudEnabled());
    expect(enabled).toBe(true);
  });

  test('status on first visit with cloud disabled mentions browser-only', async ({ page }) => {
    await page.goto('/');
    await waitForInit(page);
    await expect(page.locator('#status')).toContainText('auto-saves to this browser');
  });
});

// ─── Cloud Sync (mocked JSONBin) ─────────────────────────────────────────────

test.describe('Cloud Sync (mocked API)', () => {
  test('shows "cloud storage is empty" status when bin is empty', async ({ page }) => {
    await mockCloud(page, { data: null });
    await page.goto('/test-index.html');
    await expect(page.locator('#status')).toContainText('cloud storage is empty', { timeout: 10_000 });
    // Baseline should still render
    await expect(page.locator('.bar')).toHaveCount(14);
  });

  test('overlays cloud task positions onto the BASELINE', async ({ page }) => {
    // Move viewability to week 8 and playback to week 15
    await mockCloud(page, {
      data: [
        { id: 'viewability', s: 8, dur: 6, team: 'pubmon' },
        { id: 'playback',    s: 15, dur: 3.5, team: 'pubmon' },
      ],
    });
    await page.goto('/test-index.html');
    await expect(page.locator('#status')).toContainText('Synced from cloud', { timeout: 10_000 });

    // All 14 BASELINE bars still rendered (applyOverlay never drops tasks)
    await expect(page.locator('.bar')).toHaveCount(14);

    // viewability left = 8 * 88 = 704 px
    const vLeft = await page.locator('.bar[data-id="viewability"]').evaluate(el => el.style.left);
    expect(parseFloat(vLeft)).toBeCloseTo(8 * 88, 0);

    // playback left = 15 * 88 = 1320 px
    const pLeft = await page.locator('.bar[data-id="playback"]').evaluate(el => el.style.left);
    expect(parseFloat(pLeft)).toBeCloseTo(15 * 88, 0);
  });

  test('save now sends a PUT request with the tasks payload', async ({ page }) => {
    const puts = [];
    await page.route('**/api.jsonbin.io/**', async route => {
      if (route.request().method() === 'PUT') {
        puts.push(await route.request().postDataJSON());
        await route.fulfill({
          status: 200, contentType: 'application/json',
          body: JSON.stringify({ record: {}, metadata: { id: 'test' } }),
        });
      } else {
        await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ record: {} }) });
      }
    });

    await page.goto('/test-index.html');
    await waitForBars(page);
    await page.click('#save');
    await expect(page.locator('#status')).toContainText('Saved to cloud', { timeout: 10_000 });

    expect(puts.length).toBeGreaterThan(0);
    expect(puts[0].app).toBe('jwx-timeline');
    expect(Array.isArray(puts[0].tasks)).toBe(true);
    expect(puts[0].tasks).toHaveLength(14);
  });

  test('falls back gracefully when cloud is unreachable', async ({ page }) => {
    await mockCloud(page, { fail: true });
    await page.goto('/test-index.html');
    await expect(page.locator('#status')).toContainText('Cloud unavailable', { timeout: 10_000 });
    // Timeline must still show — render() ran before init() tried the network
    await expect(page.locator('.bar')).toHaveCount(14);
  });

  test('cloud 500 error is treated as unavailable', async ({ page }) => {
    await page.route('**/api.jsonbin.io/**', async route => {
      await route.fulfill({ status: 500, body: 'Internal Server Error' });
    });
    await page.goto('/test-index.html');
    await expect(page.locator('#status')).toContainText('Cloud unavailable', { timeout: 10_000 });
  });

  test('markDirty shows unsaved-changes indicator', async ({ page }) => {
    await mockCloud(page);
    await page.goto('/test-index.html');
    await waitForInit(page);
    // markDirty() is a global function; calling it should set the status to '● Unsaved changes'
    await page.evaluate(() => window.markDirty());
    await expect(page.locator('#status')).toContainText('Unsaved changes');
  });
});

// ─── Data model: scope / status ───────────────────────────────────────────────

test.describe('Scope & status model', () => {
  test('exported tasks carry scope and status, not type', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const dlPromise = page.waitForEvent('download');
    await page.click('#export');
    const dl = await dlPromise;
    const tmp = path.join(os.tmpdir(), `export-scope-${Date.now()}.json`);
    await dl.saveAs(tmp);
    const { tasks } = JSON.parse(fs.readFileSync(tmp, 'utf8'));
    expect(tasks).toHaveLength(14);
    for (const t of tasks) {
      expect(['MVP', 'GA']).toContain(t.scope);
      expect(['planned', 'in-dev', 'done']).toContain(t.status);
      expect(t).not.toHaveProperty('type');
      expect(t).not.toHaveProperty('dep');
    }
  });

  test('bar fill and handle are siblings, never nested', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const bar = page.locator('.bar[data-id="viewability"]');
    await expect(bar.locator('> .bar-fill')).toHaveCount(1);
    await expect(bar.locator('> .bar-label')).toHaveCount(1);
    await expect(bar.locator('> .handle')).toHaveCount(1);
    // A mask on .bar-fill must not be able to hide the resize handle.
    await expect(bar.locator('.bar-fill .handle')).toHaveCount(0);
  });

  test('scope drives the fill colour', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const mvp = await page.locator('.bar[data-id="viewability"] > .bar-fill')
      .evaluate(el => getComputedStyle(el).backgroundColor);
    const ga = await page.locator('.bar[data-id="gam"] > .bar-fill')
      .evaluate(el => getComputedStyle(el).backgroundColor);
    expect(mvp).toBe('rgb(91, 81, 198)');
    expect(ga).toBe('rgb(29, 158, 117)');
  });

  test('in-dev status is marked on the fill', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await expect(page.locator('.bar[data-id="jwdata"] > .bar-fill.indev')).toHaveCount(1);
    await expect(page.locator('.bar[data-id="viewability"] > .bar-fill.indev')).toHaveCount(0);
  });

  test('dependency chip is removed', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await expect(page.locator('#m-depchip')).toHaveCount(0);
    await expect(page.locator('.chips .chip')).toHaveCount(3);
    await expect(page.locator('.bar.violation')).toHaveCount(0);
  });
});

// ─── Status treatments ───────────────────────────────────────────────────────

test.describe('Status treatments', () => {
  test('a done bar keeps full scope colour and gains a hatch', async ({ page }) => {
    await page.goto('/');
    await page.evaluate(v2 => localStorage.setItem('jwx_timeline_state_final', v2), V2([
      { id: 'viewability', name: 'Ad viewability policy setup', team: 'pubmon', s: 3, dur: 6.5, size: 'XL', scope: 'MVP', status: 'done' },
    ]));
    await page.reload();
    await waitForBars(page);
    const fill = page.locator('.bar[data-id="viewability"] > .bar-fill');
    // scope colour is NOT degraded by being done
    expect(await fill.evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgb(91, 81, 198)');
    expect(await fill.evaluate(el => getComputedStyle(el).backgroundImage)).toContain('repeating-linear-gradient');
  });

  test('a done bar label is prefixed with a check', async ({ page }) => {
    await page.goto('/');
    await page.evaluate(v2 => localStorage.setItem('jwx_timeline_state_final', v2), V2([
      { id: 'viewability', name: 'Ad viewability policy setup', team: 'pubmon', s: 3, dur: 6.5, size: 'XL', scope: 'MVP', status: 'done' },
    ]));
    await page.reload();
    await waitForBars(page);
    await expect(page.locator('.bar[data-id="viewability"] > .bar-label')).toContainText('✓');
  });

  test('an in-dev bar is masked but its handle is not', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const fillMask = await page.locator('.bar[data-id="jwdata"] > .bar-fill')
      .evaluate(el => getComputedStyle(el).maskImage || getComputedStyle(el).webkitMaskImage);
    expect(fillMask).toContain('linear-gradient');
    const handleMask = await page.locator('.bar[data-id="jwdata"] > .handle')
      .evaluate(el => getComputedStyle(el).maskImage || getComputedStyle(el).webkitMaskImage);
    expect(handleMask === 'none' || !handleMask).toBeTruthy();
  });

  test('legend documents both scopes and both progress states', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const legend = page.locator('.legend');
    await expect(legend).toContainText('MVP scope');
    await expect(legend).toContainText('GA scope');
    await expect(legend).toContainText('Done');
    await expect(legend).toContainText('In development');
    await expect(legend.locator('.sw-done')).toHaveCount(1);
    await expect(legend.locator('.sw-indev')).toHaveCount(1);
  });
});

// ─── MVP scope toggle ────────────────────────────────────────────────────────

test.describe('MVP scope toggle', () => {
  test('every item row has an MVP toggle reflecting its scope', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await expect(page.locator('.mvpbtn')).toHaveCount(14);
    await expect(page.locator('.mvpbtn[data-id="viewability"]')).toHaveClass(/\bon\b/);
    await expect(page.locator('.mvpbtn[data-id="gam"]')).not.toHaveClass(/\bon\b/);
  });

  test('toggling scope repaints the bar', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await page.click('.mvpbtn[data-id="gam"]');
    await expect(page.locator('.bar[data-id="gam"] > .bar-fill'))
      .toHaveCSS('background-color', 'rgb(91, 81, 198)');
    await expect(page.locator('.mvpbtn[data-id="gam"]')).toHaveClass(/\bon\b/);
  });

  test('deselecting the latest MVP item pulls the MVP date earlier', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    // BASELINE MVP ends: playback 9.5+3.5 = 13 is the latest
    const before = await page.locator('#m-mvp').textContent();
    await page.click('.mvpbtn[data-id="playback"]');
    const after = await page.locator('#m-mvp').textContent();
    expect(after).not.toBe(before);
    // toggling back restores it
    await page.click('.mvpbtn[data-id="playback"]');
    await expect(page.locator('#m-mvp')).toHaveText(before);
  });

  test('scope survives a reload', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await page.click('.mvpbtn[data-id="gam"]');
    await page.click('#save');
    await page.reload();
    await waitForBars(page);
    await expect(page.locator('.mvpbtn[data-id="gam"]')).toHaveClass(/\bon\b/);
  });
});

// ─── Status cycle ────────────────────────────────────────────────────────────

test.describe('Status cycle', () => {
  test('the pill shows the current status', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    await expect(page.locator('.statbtn')).toHaveCount(14);
    await expect(page.locator('.statbtn[data-id="jwdata"]')).toHaveText('in dev');
    await expect(page.locator('.statbtn[data-id="viewability"]')).toHaveText('planned');
  });

  test('clicking cycles planned to in dev to done and back', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const pill = page.locator('.statbtn[data-id="viewability"]');
    await pill.click();
    await expect(pill).toHaveText('in dev');
    await pill.click();
    await expect(pill).toHaveText('done');
    await expect(page.locator('.bar[data-id="viewability"] > .bar-fill.done')).toHaveCount(1);
    await pill.click();
    await expect(pill).toHaveText('planned');
  });

  test('marking the latest MVP item done does NOT move the MVP date', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const before = await page.locator('#m-mvp').textContent();
    const gaBefore = await page.locator('#m-ga').textContent();
    const pill = page.locator('.statbtn[data-id="playback"]');
    await pill.click();
    await pill.click();
    await expect(pill).toHaveText('done');
    await expect(page.locator('#m-mvp')).toHaveText(before);
    await expect(page.locator('#m-ga')).toHaveText(gaBefore);
  });

  test('done state survives a reload', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const pill = page.locator('.statbtn[data-id="gam"]');
    await pill.click();
    await pill.click();
    await page.click('#save');
    await page.reload();
    await waitForBars(page);
    await expect(page.locator('.statbtn[data-id="gam"]')).toHaveText('done');
    await expect(page.locator('.bar[data-id="gam"] > .bar-fill.done')).toHaveCount(1);
  });

  test('a done bar is still draggable', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    const pill = page.locator('.statbtn[data-id="gam"]');
    await pill.click();
    await pill.click();
    const bar = page.locator('.bar[data-id="gam"]');
    const before = parseFloat(await bar.evaluate(el => el.style.left));
    const box = await bar.boundingBox();
    await page.mouse.move(box.x + 20, box.y + box.height / 2);
    await page.mouse.down();
    await page.mouse.move(box.x + 20 + 88, box.y + box.height / 2, { steps: 8 });
    await page.mouse.up();
    const after = parseFloat(await page.locator('.bar[data-id="gam"]').evaluate(el => el.style.left));
    expect(after).toBeGreaterThan(before);
  });
});

// ─── Delete items ────────────────────────────────────────────────────────────

test.describe('Delete work items', () => {
  test('confirming removes the item', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    page.once('dialog', d => d.accept());
    await page.click('.irm[data-id="midrolls"]');
    await expect(page.locator('.bar')).toHaveCount(13);
    await expect(page.locator('.bar[data-id="midrolls"]')).toHaveCount(0);
  });

  test('dismissing the confirm keeps the item', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    page.once('dialog', d => d.dismiss());
    await page.click('.irm[data-id="midrolls"]');
    await page.waitForTimeout(300);
    await expect(page.locator('.bar')).toHaveCount(14);
  });

  test('a deleted item stays deleted after reload', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    page.once('dialog', d => d.accept());
    await page.click('.irm[data-id="midrolls"]');
    await page.click('#save');
    await page.reload();
    await waitForBars(page);
    await expect(page.locator('.bar')).toHaveCount(13);
    await expect(page.locator('.bar[data-id="midrolls"]')).toHaveCount(0);
  });

  test('the item delete button does not collide with the team one', async ({ page }) => {
    await page.goto('/');
    await waitForBars(page);
    // .lrm belongs to lane headers only; item rows use .irm
    await expect(page.locator('.row .gut .lrm')).toHaveCount(0);
    await expect(page.locator('.lhead .irm')).toHaveCount(0);
  });

  test('deleting every item leaves a working empty page that survives reload', async ({ page }) => {
    await page.goto('/');
    await page.evaluate(v2 => localStorage.setItem('jwx_timeline_state_final', v2), V2([
      { id: 'solo', name: 'Last one', team: 'auction', s: 0, dur: 1, size: 'M', scope: 'GA', status: 'planned' },
    ]));
    await page.reload();
    await waitForBars(page);
    page.once('dialog', d => d.accept());
    await page.click('.irm[data-id="solo"]');
    await expect(page.locator('.bar')).toHaveCount(0);
    await expect(page.locator('#m-mvp')).toHaveText('—');
    await expect(page.locator('#m-ga')).toHaveText('—');
    await page.click('#save');
    await page.reload();
    await waitForInit(page);
    await expect(page.locator('.bar')).toHaveCount(0);   // BASELINE must NOT come back
    await expect(page.locator('#status')).toContainText('No work items');
  });
});
